# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/iv3jjh/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com"

[social.params]
icon = "brand-instagram"
